# Generated by Django 5.2.1 on 2025-08-24 23:00

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "nni",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Numéro National d'Identité",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Adresse e-mail",
                    ),
                ),
                ("failed_login_attempts", models.IntegerField(default=0)),
                ("is_locked", models.BooleanField(default=False)),
                ("lockout_time", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Groupes auxquels appartient cet utilisateur.",
                        related_name="customuser_set",
                        related_query_name="customuser",
                        to="auth.group",
                        verbose_name="Groupes",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Permissions spécifiques de cet utilisateur.",
                        related_name="customuser_set",
                        related_query_name="customuser",
                        to="auth.permission",
                        verbose_name="Permissions utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nomEcole",
                    models.CharField(
                        max_length=50, null=True, verbose_name="Nom de l'école"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, null=True, verbose_name="Code école"
                    ),
                ),
                (
                    "niveau",
                    models.CharField(
                        default="N/A", max_length=50, verbose_name="Niveau scolaire"
                    ),
                ),
                (
                    "nomMoughatta",
                    models.CharField(
                        choices=[
                            ("adel_bagrou", "Adel Bagrou"),
                            ("aïoun", "Aïoun"),
                            ("akjoujt", "Akjoujt"),
                            ("aleg", "Aleg"),
                            ("amourj", "Amourj"),
                            ("aoujeft", "Aoujeft"),
                            ("arafat", "Arafat"),
                            ("atar", "Atar"),
                            ("bababé", "Bababé"),
                            ("barkéol", "Barkéol"),
                            ("bassiknou", "Bassiknou"),
                            ("bénichab", "Bénichab"),
                            ("bir_moghreïn", "Bir Moghreïn"),
                            ("bogué", "Bogué"),
                            ("boumdeid", "Boumdeid"),
                            ("boutilimit", "Boutilimit"),
                            ("chami", "Chami"),
                            ("chinguetti", "Chinguetti"),
                            ("dar_naïm", "Dar Naïm"),
                            ("djigueni", "Djigueni"),
                            ("el_mina", "El Mina"),
                            ("f_deírick", "F'Déirick"),
                            ("ghabou", "Ghabou"),
                            ("guérou", "Guérou"),
                            ("kaédi", "Kaédi"),
                            ("kankossa", "Kankossa"),
                            ("keur_macène", "Keur Macène"),
                            ("kiffa", "Kiffa"),
                            ("koubenni", "Koubenni"),
                            ("ksar", "Ksar"),
                            ("lexeiba", "Lexeiba"),
                            ("m_bagne", "M'Bagne"),
                            ("m_bout", "M'Bout"),
                            ("maghama", "Maghama"),
                            ("magta_lahjar", "Magta Lahjar"),
                            ("male", "Male"),
                            ("méderdra", "Méderdra"),
                            ("monguel", "Monguel"),
                            ("moudjéria", "Moudjéria"),
                            ("n_beiket_lehwach", "N'Beiket Lehwach"),
                            ("néma", "Néma"),
                            ("nouadhibou", "Nouadhibou"),
                            ("ouad_naga", "Ouad Naga"),
                            ("ouadane", "Ouadane"),
                            ("oualata", "Oualata"),
                            ("ould_yengé", "Ould Yengé"),
                            ("r_kiz", "R'Kiz"),
                            ("riyad", "Riyad"),
                            ("rosso", "Rosso"),
                            ("sebkha", "Sebkha"),
                            ("sélibaby", "Sélibaby"),
                            ("tamchekett", "Tamchekett"),
                            ("tékane", "Tékane"),
                            ("tevragh_zeina", "Tevragh Zeina"),
                            ("teyarett", "Teyarett"),
                            ("tichitt", "Tichitt"),
                            ("tidjikja", "Tidjikja"),
                            ("timbédra", "Timbédra"),
                            ("tintane", "Tintane"),
                            ("touil", "Touil"),
                            ("toujounine", "Toujounine"),
                            ("wompou", "Wompou"),
                            ("zouérate", "Zouérate"),
                        ],
                        default="N/A",
                        max_length=50,
                        verbose_name="Moughataa",
                    ),
                ),
                (
                    "idMoughatta",
                    models.IntegerField(null=True, verbose_name="ID Moughataa"),
                ),
                (
                    "wilaya",
                    models.CharField(
                        choices=[
                            ("adrar", "Adrar"),
                            ("assaba", "Assaba"),
                            ("brakna", "Brakna"),
                            ("dakhlet_nouadhibou", "Dakhlet Nouadhibou"),
                            ("gorgol", "Gorgol"),
                            ("guidimakha", "Guidimakha"),
                            ("hodh_charghi", "Hodh Charghi"),
                            ("hodh_gharb", "Hodh Gharbi"),
                            ("inchiri", "Inchiri"),
                            ("nouakchott_nord", "Nouakchott Nord"),
                            ("nouakchott_ouest", "Nouakchott Ouest"),
                            ("nouakchott_sud", "Nouakchott Sud"),
                            ("tagant", "Tagant"),
                            ("tiris_zemmour", "Tiris Zemmour"),
                            ("trarza", "Trarza"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Wilaya",
                    ),
                ),
                (
                    "numTel",
                    models.CharField(
                        max_length=50, null=True, verbose_name="Téléphone"
                    ),
                ),
                ("nni", models.CharField(max_length=50, null=True, verbose_name="NNI")),
                ("nom", models.CharField(max_length=50, null=True, verbose_name="Nom")),
                (
                    "nationalite",
                    models.CharField(
                        max_length=50, null=True, verbose_name="Nationalité"
                    ),
                ),
                (
                    "diplome",
                    models.CharField(max_length=50, null=True, verbose_name="Diplôme"),
                ),
                (
                    "dateLettreWaly",
                    models.DateField(verbose_name="Date de la lettre Waly"),
                ),
                (
                    "numLettreWaly",
                    models.CharField(
                        max_length=50,
                        null=True,
                        verbose_name="Numéro de la lettre Waly",
                    ),
                ),
                (
                    "qr_uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, null=True, unique=True
                    ),
                ),
                (
                    "codeLR",
                    models.CharField(max_length=50, null=True, verbose_name="Code LR"),
                ),
                (
                    "lienQR",
                    models.CharField(max_length=200, null=True, verbose_name="Lien QR"),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="generated_pdfs/",
                        verbose_name="Fichier PDF",
                    ),
                ),
                ("dateAjout", models.DateField(verbose_name="Date d'ajout")),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DirectorAuthorization",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nom",
                    models.CharField(
                        default="N/A", max_length=50, verbose_name="Nom complet"
                    ),
                ),
                (
                    "nni",
                    models.CharField(default="N/A", max_length=50, verbose_name="NNI"),
                ),
                (
                    "lieuNai",
                    models.CharField(
                        default="N/A", max_length=50, verbose_name="Lieu de naissance"
                    ),
                ),
                ("dateNais", models.DateField(verbose_name="Date de naissance")),
                (
                    "sourceDiplome",
                    models.CharField(
                        default="N/A", max_length=50, verbose_name="Source du diplôme"
                    ),
                ),
                (
                    "numDiplome",
                    models.CharField(
                        default="N/A", max_length=50, verbose_name="Numéro du diplôme"
                    ),
                ),
                (
                    "specialiteDiplome",
                    models.CharField(
                        default="N/A",
                        max_length=50,
                        verbose_name="Spécialité du diplôme",
                    ),
                ),
                (
                    "niveauDiplom",
                    models.CharField(
                        default="N/A", max_length=50, verbose_name="Niveau du diplôme"
                    ),
                ),
                (
                    "typeAutorisationDirige",
                    models.CharField(
                        default="N/A",
                        max_length=200,
                        verbose_name="Type d'autorisation",
                    ),
                ),
                (
                    "dateAutorisation",
                    models.DateField(verbose_name="Date d'autorisation"),
                ),
                (
                    "autorisationNum",
                    models.CharField(
                        default="N/A",
                        max_length=50,
                        verbose_name="Numéro d'autorisation",
                    ),
                ),
                ("dateDebut", models.DateField(verbose_name="Date de début")),
                ("dateFin", models.DateField(verbose_name="Date de fin")),
                (
                    "numTel",
                    models.CharField(
                        default="N/A", max_length=50, verbose_name="Téléphone"
                    ),
                ),
                (
                    "nomMoughatta",
                    models.CharField(
                        choices=[
                            ("adel_bagrou", "Adel Bagrou"),
                            ("aïoun", "Aïoun"),
                            ("akjoujt", "Akjoujt"),
                            ("aleg", "Aleg"),
                            ("amourj", "Amourj"),
                            ("aoujeft", "Aoujeft"),
                            ("arafat", "Arafat"),
                            ("atar", "Atar"),
                            ("bababé", "Bababé"),
                            ("barkéol", "Barkéol"),
                            ("bassiknou", "Bassiknou"),
                            ("bénichab", "Bénichab"),
                            ("bir_moghreïn", "Bir Moghreïn"),
                            ("bogué", "Bogué"),
                            ("boumdeid", "Boumdeid"),
                            ("boutilimit", "Boutilimit"),
                            ("chami", "Chami"),
                            ("chinguetti", "Chinguetti"),
                            ("dar_naïm", "Dar Naïm"),
                            ("djigueni", "Djigueni"),
                            ("el_mina", "El Mina"),
                            ("f_deírick", "F'Déirick"),
                            ("ghabou", "Ghabou"),
                            ("guérou", "Guérou"),
                            ("kaédi", "Kaédi"),
                            ("kankossa", "Kankossa"),
                            ("keur_macène", "Keur Macène"),
                            ("kiffa", "Kiffa"),
                            ("koubenni", "Koubenni"),
                            ("ksar", "Ksar"),
                            ("lexeiba", "Lexeiba"),
                            ("m_bagne", "M'Bagne"),
                            ("m_bout", "M'Bout"),
                            ("maghama", "Maghama"),
                            ("magta_lahjar", "Magta Lahjar"),
                            ("male", "Male"),
                            ("méderdra", "Méderdra"),
                            ("monguel", "Monguel"),
                            ("moudjéria", "Moudjéria"),
                            ("n_beiket_lehwach", "N'Beiket Lehwach"),
                            ("néma", "Néma"),
                            ("nouadhibou", "Nouadhibou"),
                            ("ouad_naga", "Ouad Naga"),
                            ("ouadane", "Ouadane"),
                            ("oualata", "Oualata"),
                            ("ould_yengé", "Ould Yengé"),
                            ("r_kiz", "R'Kiz"),
                            ("riyad", "Riyad"),
                            ("rosso", "Rosso"),
                            ("sebkha", "Sebkha"),
                            ("sélibaby", "Sélibaby"),
                            ("tamchekett", "Tamchekett"),
                            ("tékane", "Tékane"),
                            ("tevragh_zeina", "Tevragh Zeina"),
                            ("teyarett", "Teyarett"),
                            ("tichitt", "Tichitt"),
                            ("tidjikja", "Tidjikja"),
                            ("timbédra", "Timbédra"),
                            ("tintane", "Tintane"),
                            ("touil", "Touil"),
                            ("toujounine", "Toujounine"),
                            ("wompou", "Wompou"),
                            ("zouérate", "Zouérate"),
                        ],
                        default="N/A",
                        max_length=50,
                        verbose_name="Moughataa",
                    ),
                ),
                (
                    "wilaya",
                    models.CharField(
                        choices=[
                            ("adrar", "Adrar"),
                            ("assaba", "Assaba"),
                            ("brakna", "Brakna"),
                            ("dakhlet_nouadhibou", "Dakhlet Nouadhibou"),
                            ("gorgol", "Gorgol"),
                            ("guidimakha", "Guidimakha"),
                            ("hodh_charghi", "Hodh Charghi"),
                            ("hodh_gharb", "Hodh Gharbi"),
                            ("inchiri", "Inchiri"),
                            ("nouakchott_nord", "Nouakchott Nord"),
                            ("nouakchott_ouest", "Nouakchott Ouest"),
                            ("nouakchott_sud", "Nouakchott Sud"),
                            ("tagant", "Tagant"),
                            ("tiris_zemmour", "Tiris Zemmour"),
                            ("trarza", "Trarza"),
                        ],
                        default="N/A",
                        max_length=50,
                        verbose_name="Wilaya",
                    ),
                ),
                (
                    "idMoughatta",
                    models.IntegerField(null=True, verbose_name="ID Moughataa"),
                ),
                (
                    "noter",
                    models.CharField(
                        default="N/A", max_length=50, verbose_name="Notaire"
                    ),
                ),
                (
                    "dateAutorisationNoter",
                    models.DateField(verbose_name="Date de l'autorisation notaire"),
                ),
                (
                    "numAutorisationNoter",
                    models.CharField(
                        default="N/A",
                        max_length=50,
                        verbose_name="Numéro d'autorisation notaire",
                    ),
                ),
                (
                    "codeAD",
                    models.CharField(
                        default="N/A", max_length=50, verbose_name="Code AD"
                    ),
                ),
                (
                    "lienQR",
                    models.URLField(blank=True, null=True, verbose_name="Lien QR"),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="pdfs/",
                        verbose_name="Fichier PDF",
                    ),
                ),
                ("dateAjout", models.DateField(verbose_name="Date d'ajout")),
                (
                    "qr_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="director_authorizations",
                        to="db.school",
                        verbose_name="École",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeacherAuthorization",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "degree",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Diplôme"
                    ),
                ),
                (
                    "matierEnseigner",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Matière enseignée",
                    ),
                ),
                (
                    "sourceDiplome",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Source du diplôme",
                    ),
                ),
                (
                    "numDiplome",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Numéro du diplôme",
                    ),
                ),
                (
                    "specialiteDiplome",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Spécialité du diplôme",
                    ),
                ),
                (
                    "niveauDiplom",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Niveau du diplôme",
                    ),
                ),
                (
                    "lieuNai",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Lieu de naissance",
                    ),
                ),
                (
                    "dateNais",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de naissance"
                    ),
                ),
                (
                    "nni",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="NNI"
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Nom complet"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Code"
                    ),
                ),
                (
                    "codeAE",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Code AE"
                    ),
                ),
                (
                    "qr_code",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Code QR"
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="pdfs/",
                        verbose_name="Fichier PDF",
                    ),
                ),
                ("dateAjout", models.DateField(verbose_name="Date d'ajout")),
                ("dateDebut", models.DateField(verbose_name="Date de début")),
                ("dateFin", models.DateField(verbose_name="Date de fin")),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "qr_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_authorizations",
                        to="db.school",
                        verbose_name="École",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
        ),
    ]
