# Generated by Django 5.2.1 on 2025-08-11 11:50

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("diplome", models.CharField(max_length=50, null=True)),
                ("dateLettreWaly", models.DateField()),
                ("numLettreWaly", models.CharField(max_length=50, null=True)),
                ("numTel", models.CharField(max_length=50, null=True)),
                ("nomMoughatta", models.CharField(default="N/A", max_length=50)),
                ("idMoughatta", models.IntegerField(null=True)),
                ("wilaya", models.CharField(max_length=50, null=True)),
                ("nomEcole", models.CharField(max_length=50, null=True)),
                ("code", models.CharField(max_length=20, null=True)),
                ("nni", models.CharField(max_length=50, null=True)),
                ("nom", models.CharField(max_length=50, null=True)),
                ("codeLR", models.CharField(max_length=50, null=True)),
                ("lienQR", models.CharField(max_length=200, null=True)),
                ("nationalite", models.CharField(max_length=50, null=True)),
                ("niveau", models.CharField(default="N/A", max_length=50)),
                ("dateAjout", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "nni",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="National ID"
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to.",
                        related_name="customuser_set",
                        related_query_name="customuser",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="customuser_set",
                        related_query_name="customuser",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="DirectorAuthorization",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("noter", models.CharField(default="N/A", max_length=50)),
                ("dateAutorisationNoter", models.DateField()),
                (
                    "numAutorisationNoter",
                    models.CharField(default="N/A", max_length=50),
                ),
                ("numTel", models.CharField(default="N/A", max_length=50)),
                ("nomMoughatta", models.CharField(default="N/A", max_length=50)),
                ("idMoughatta", models.IntegerField(null=True)),
                ("wilaya", models.CharField(default="N/A", max_length=50)),
                ("dateAutorisation", models.DateField()),
                ("autorisationNum", models.CharField(default="N/A", max_length=50)),
                ("nomEcole", models.CharField(default="N/A", max_length=50)),
                ("sourceDiplome", models.CharField(default="N/A", max_length=50)),
                ("numDiplome", models.CharField(default="N/A", max_length=50)),
                ("specialiteDiplome", models.CharField(default="N/A", max_length=50)),
                ("niveauDiplom", models.CharField(default="N/A", max_length=50)),
                ("lieuNai", models.CharField(default="N/A", max_length=50)),
                ("dateNais", models.DateField()),
                ("nni", models.CharField(default="N/A", max_length=50)),
                ("nom", models.CharField(default="N/A", max_length=50)),
                ("codeAD", models.CharField(default="N/A", max_length=50)),
                ("lienQR", models.CharField(default="N/A", max_length=200)),
                (
                    "typeAutorisationDirige",
                    models.CharField(default="N/A", max_length=200),
                ),
                ("dateAjout", models.DateField()),
                ("dateDebut", models.DateField()),
                ("dateFin", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="director_authorizations",
                        to="db.school",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeacherAuthorization",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("degree", models.CharField(max_length=50, null=True)),
                ("matierEnseigner", models.CharField(max_length=50, null=True)),
                ("sourceDiplome", models.CharField(max_length=50, null=True)),
                ("numDiplome", models.CharField(max_length=50, null=True)),
                ("specialiteDiplome", models.CharField(max_length=50, null=True)),
                ("niveauDiplom", models.CharField(max_length=50, null=True)),
                ("lieuNai", models.CharField(max_length=50, null=True)),
                ("dateNais", models.CharField(max_length=50, null=True)),
                ("nni", models.CharField(max_length=50, null=True)),
                ("nom", models.CharField(max_length=50, null=True)),
                ("code", models.CharField(max_length=50, null=True)),
                ("codeAE", models.CharField(max_length=50, null=True)),
                ("qr_code", models.CharField(blank=True, max_length=50, null=True)),
                ("dateAjout", models.DateField()),
                ("dateDebut", models.DateField()),
                ("dateFin", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_authorizations",
                        to="db.school",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
