# Generated by Django 5.2.1 on 2025-08-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="directorauthorization",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="pdfs/"),
        ),
        migrations.AddField(
            model_name="teacherauthorization",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="pdfs/"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_permissions",
            field=models.ManyToManyField(
                help_text="Specific permissions for this user.",
                related_name="customuser_set",
                related_query_name="customuser",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AlterField(
            model_name="teacherauthorization",
            name="code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="teacherauthorization",
            name="codeAE",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="teacherauthorization",
            name="dateNais",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="teacherauthorization",
            name="degree",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="teacherauthorization",
            name="lieuNai",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="teacherauthorization",
            name="matierEnseigner",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="teacherauthorization",
            name="niveauDiplom",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="teacherauthorization",
            name="nni",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="teacherauthorization",
            name="nom",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="teacherauthorization",
            name="numDiplome",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="teacherauthorization",
            name="sourceDiplome",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="teacherauthorization",
            name="specialiteDiplome",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
