# Generated by Django 5.2.1 on 2025-08-24 23:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0002_alter_directorauthorization_qr_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directorauthorization",
            name="qr_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="school",
            name="qr_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="teacherauthorization",
            name="qr_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
