# Generated by Django 5.2.1 on 2025-08-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0005_alter_directorauthorization_idmoughatta_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="dateAjout",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
