# Generated by Django 5.2.1 on 2025-08-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0006_alter_school_dateajout"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="generated_pdfs/"),
        ),
    ]
