# Generated by Django 5.2.1 on 2025-08-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0007_school_pdf_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="qr_file",
            field=models.FileField(blank=True, null=True, upload_to="generated_qr/"),
        ),
    ]
