# Generated by Django 5.2.1 on 2025-08-15 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0008_school_qr_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="school",
            name="qr_file",
        ),
    ]
