# Generated by Django 5.2.1 on 2025-08-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0009_remove_school_qr_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="dateAjout",
            field=models.DateField(),
        ),
    ]
