# Generated by Django 5.2.1 on 2025-08-16 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0010_alter_school_dateajout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacherauthorization",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
