# Generated by Django 5.2.1 on 2025-08-18 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0013_alter_school_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directorauthorization",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="director_authorizations",
                to="db.school",
            ),
        ),
    ]
